Location.create!([
  {name: "Seattle", city: "Seattle", state: "WA"},
  {name: "Chicago", city: "Chicago", state: "IL"},
  {name: "San Jose", city: "San Jose", state: "CA"},
  {name: "Web", city: "San Jose", state: "CA"}
])

Language.create!([
  {name: "Python"},
  {name: "Ruby"},
  {name: "Mean"}
])

Instructor.create!([
  {name: "Mike Hannon", email: "mike@codingdojo.com",    location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Speros M",    email: "sperose@codingdojo.com", location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Sudo David",  email: "david@codingdojo.com",   location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Chris",       email: "chris@codingdojo.com",   location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Donovan",     email: "donovan@codingdojo.com", location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "John Doe",    email: "john@codingdojo.com",    location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Tim Chen",    email: "tim@codingdojo.com",     location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Sara Wong",   email: "sara@codingdojo.com",    location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Mad Jack",    email: "jack@codingdojo.com",    location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil},
  {name: "Mad Jack",    email: "jdack@codingdojo.com",    location_id: 1, linkedin: nil, website: nil, password_digest: "$2a$10$hrSZdD1q6lcBYWZ7J6c.Rerh90e.V9ycrPgoWyud.X5sms08wK8vi", about: "This is a short note about me", admin: true, active: true, avatar_file_name: nil, avatar_content_type: nil, avatar_file_size: nil, avatar_updated_at: nil}
])

Cohort.create!([  {
    location_id: 1,
    start: "9/1/2015",
    active: FALSE,
    created_at: "9/1/2015",
    updated_at: "9/1/2015"
  },
  {
    location_id: 1,
    start: "10/1/2015",
    active: FALSE,
    created_at: "10/1/2015",
    updated_at: "10/1/2015"
  },
  {
    location_id: 1,
    start: "11/1/2015",
    active: FALSE,
    created_at: "11/1/2015",
    updated_at: "11/1/2015"
  },
  {
    location_id: 1,
    start: "12/1/2015",
    active: FALSE,
    created_at: "12/1/2015",
    updated_at: "12/1/2015"
  },
  {
    location_id: 1,
    start: "1/1/2016",
    active: FALSE,
    created_at: "1/1/2016",
    updated_at: "1/1/2016"
  },
  {
    location_id: 1,
    start: "2/1/2016",
    active: FALSE,
    created_at: "2/1/2016",
    updated_at: "2/1/2016"
  },
  {
    location_id: 1,
    start: "3/1/2016",
    active: FALSE,
    created_at: "3/1/2016",
    updated_at: "3/1/2016"
  },
  {
    location_id: 1,
    start: "4/1/2016",
    active: FALSE,
    created_at: "4/1/2016",
    updated_at: "4/1/2016"
  },
  {
    location_id: 1,
    start: "5/1/2016",
    active: TRUE,
    created_at: "5/1/2016",
    updated_at: "5/1/2016"
  },
  {
    location_id: 1,
    start: "6/1/2016",
    active: TRUE,
    created_at: "6/1/2016",
    updated_at: "6/1/2016"
  },
  {
    location_id: 1,
    start: "7/1/2016",
    active: TRUE,
    created_at: "7/1/2016",
    updated_at: "7/1/2016"
  },
  {
    location_id: 1,
    start: "8/1/2016",
    active: TRUE,
    created_at: "8/1/2016",
    updated_at: "8/1/2016"
  },
  {
    location_id: 1,
    start: "9/1/2016",
    active: FALSE,
    created_at: "9/1/2016",
    updated_at: "9/1/2016"
  },
  {
    location_id: 1,
    start: "10/1/2016",
    active: FALSE,
    created_at: "10/1/2016",
    updated_at: "10/1/2016"
  }])

Student.create!([
  {
    name: "Phillip Perkins",
    email: "s@gmail.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Clarence Andrews",
    email: "candrews1@imdb.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Rebecca Hart",
    email: "rhart2@networksolutions.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Judith Hall",
    email: "jhall3@jiathis.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Patricia Hansen",
    email: "phansen4@about.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Louise Vasquez",
    email: "lvasquez5@51.la",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Matthew Robinson",
    email: "mrobinson6@mapy.cz",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Ruby Mills",
    email: "rmills7@etsy.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Anthony Castillo",
    email: "acastillo8@craigslist.org",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Sara Webb",
    email: "swebb9@desdev.cn",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Joyce Lawrence",
    email: "jlawrencea@yahoo.co.jp",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Tammy Howard",
    email: "thowardb@friendfeed.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Deborah Olson",
    email: "dolsonc@nih.gov",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Terry Green",
    email: "tgreend@fc2.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Albert Snyder",
    email: "asnydere@barnesandnoble.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "James Henry",
    email: "jhenryf@tinyurl.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Harry Gomez",
    email: "hgomezg@addtoany.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Gregory Ellis",
    email: "gellish@hc360.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Elizabeth Kelly",
    email: "ekellyi@t-online.de",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jeffrey Bryant",
    email: "jbryantj@wix.com",
    cohort_id: 1,
    created_at: "8/1/2015",
    updated_at: "8/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Daniel Thompson",
    email: "dthompsonk@google.co.uk",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Johnny Richardson",
    email: "jrichardsonl@nps.gov",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jesse Ford",
    email: "jfordm@php.net",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Raymond Mitchell",
    email: "rmitchelln@ocn.ne.jp",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Andrea Lopez",
    email: "alopezo@twitpic.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Stephanie Thompson",
    email: "sthompsonp@clickbank.net",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Lisa Marshall",
    email: "lmarshallq@tumblr.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Cheryl Fernandez",
    email: "cfernandezr@latimes.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Amy Holmes",
    email: "aholmess@google.com.au",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Eugene Cunningham",
    email: "ecunninghamt@jiathis.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Christine Murray",
    email: "cmurrayu@t-online.de",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Matthew Chapman",
    email: "mchapmanv@mapquest.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Gregory Scott",
    email: "gscottw@netvibes.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Henry Morris",
    email: "hmorrisx@time.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Julia Hernandez",
    email: "jhernandezy@sbwire.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "James Weaver",
    email: "jweaverz@hugedomains.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Cheryl Fisher",
    email: "cfisher10@chronoengine.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Timothy Hughes",
    email: "thughes11@cyberchimps.com",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Joseph Daniels",
    email: "jdaniels12@ucoz.ru",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Margaret Ramos",
    email: "mramos13@uiuc.edu",
    cohort_id: 2,
    created_at: "9/1/2015",
    updated_at: "9/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Lawrence Lewis",
    email: "llewis14@adobe.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Antonio Porter",
    email: "aporter15@yellowpages.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Sara Romero",
    email: "sromero16@behance.net",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Ryan Berry",
    email: "rberry17@squarespace.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Anne Richardson",
    email: "arichardson18@economist.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Sara Reyes",
    email: "sreyes19@narod.ru",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Wayne Cox",
    email: "wcox1a@apache.org",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Eugene Payne",
    email: "epayne1b@unesco.org",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jeremy Howard",
    email: "jhoward1c@freewebs.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Mildred Nichols",
    email: "mnichols1d@phpbb.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Juan Wood",
    email: "jwood1e@patch.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Victor Chapman",
    email: "vchapman1f@wix.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Johnny Webb",
    email: "jwebb1g@hibu.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Russell Ray",
    email: "rray1h@yelp.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Alan Henderson",
    email: "ahenderson1i@wired.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Nancy Payne",
    email: "npayne1j@xrea.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jacqueline Washington",
    email: "jwashington1k@bluehost.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Todd Daniels",
    email: "tdaniels1l@slideshare.net",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Larry Miller",
    email: "lmiller1m@amazonaws.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Doris Riley",
    email: "driley1n@chronoengine.com",
    cohort_id: 3,
    created_at: "10/1/2015",
    updated_at: "10/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Ronald Diaz",
    email: "rdiaz1o@geocities.jp",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Martha Frazier",
    email: "mfrazier1p@ucsd.edu",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Paula Nguyen",
    email: "pnguyen1q@jiathis.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Raymond Johnston",
    email: "rjohnston1r@europa.eu",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Chris Watson",
    email: "cwatson1s@posterous.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Peter Knight",
    email: "pknight1t@amazon.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Anne Grant",
    email: "agrant1u@vistaprint.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Robert Mason",
    email: "rmason1v@smh.com.au",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Nancy Stephens",
    email: "nstephens1w@techcrunch.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Marilyn Crawford",
    email: "mcrawford1x@columbia.edu",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Kevin Sullivan",
    email: "ksullivan1y@vk.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Carolyn Cooper",
    email: "ccooper1z@kickstarter.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Deborah Johnston",
    email: "djohnston20@clickbank.net",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Clarence Mills",
    email: "cmills21@webeden.co.uk",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Frank Lawson",
    email: "flawson22@netscape.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Martha Kim",
    email: "mkim23@alibaba.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Amy Snyder",
    email: "asnyder24@gravatar.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Rose Griffin",
    email: "rgriffin25@squarespace.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Roy West",
    email: "rwest26@blogtalkradio.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Willie Gibson",
    email: "wgibson27@foxnews.com",
    cohort_id: 4,
    created_at: "11/1/2015",
    updated_at: "11/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Justin Gray",
    email: "jgray28@networksolutions.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Robin Anderson",
    email: "randerson29@usatoday.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Craig Campbell",
    email: "ccampbell2a@godaddy.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Gregory Weaver",
    email: "gweaver2b@answers.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Nicholas Richardson",
    email: "nrichardson2c@shop-pro.jp",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Jane Scott",
    email: "jscott2d@sakura.ne.jp",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Kathy Wilson",
    email: "kwilson2e@usda.gov",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Henry Burns",
    email: "hburns2f@guardian.co.uk",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Clarence Collins",
    email: "ccollins2g@yelp.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Sarah George",
    email: "sgeorge2h@amazon.de",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Patrick Gibson",
    email: "pgibson2i@samsung.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Mary Marshall",
    email: "mmarshall2j@blogger.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Rachel Mendoza",
    email: "rmendoza2k@youtube.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Laura Morris",
    email: "lmorris2l@ovh.net",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jennifer Moore",
    email: "jmoore2m@nsw.gov.au",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Marie Lawson",
    email: "mlawson2n@zimbio.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Rachel Hamilton",
    email: "rhamilton2o@hexun.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Michael Holmes",
    email: "mholmes2p@cloudflare.com",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Susan Sims",
    email: "ssims2q@cdc.gov",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Lori Bishop",
    email: "lbishop2r@a8.net",
    cohort_id: 5,
    created_at: "12/1/2015",
    updated_at: "12/1/2015",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Pamela Freeman",
    email: "pfreeman2s@deviantart.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Lisa Gomez",
    email: "lgomez2t@shop-pro.jp",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Kevin Lane",
    email: "klane2u@about.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Terry Welch",
    email: "twelch2v@bravesites.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Terry Black",
    email: "tblack2w@comsenz.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Joshua Wright",
    email: "jwright2x@bbb.org",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Shirley Young",
    email: "syoung2y@abc.net.au",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Nicole Boyd",
    email: "nboyd2z@webnode.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Joyce Sanchez",
    email: "jsanchez30@nationalgeographic.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Steve Patterson",
    email: "spatterson31@hc360.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Steve Carroll",
    email: "scarroll32@opera.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Roger Cox",
    email: "rcox33@51.la",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Joyce Barnes",
    email: "jbarnes34@opera.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Anne Campbell",
    email: "acampbell35@yahoo.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Alice Reid",
    email: "areid36@dailymotion.com",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Brandon Garrett",
    email: "bgarrett37@ebay.co.uk",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Roger Bryant",
    email: "rbryant38@mapy.cz",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Russell Simmons",
    email: "rsimmons39@npr.org",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Christine Davis",
    email: "cdavis3a@rakuten.co.jp",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Ruth Daniels",
    email: "rdaniels3b@altervista.org",
    cohort_id: 6,
    created_at: "1/1/2016",
    updated_at: "1/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Jennifer Bennett",
    email: "jbennett3c@pbs.org",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jeffrey Cruz",
    email: "jcruz3d@histats.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Kelly Ramirez",
    email: "kramirez3e@wunderground.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Christine Shaw",
    email: "cshaw3f@earthlink.net",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Annie Wilson",
    email: "awilson3g@ftc.gov",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Emily King",
    email: "eking3h@opera.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Heather Gonzales",
    email: "hgonzales3i@unc.edu",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Michelle Hart",
    email: "mhart3j@salon.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Teresa Rogers",
    email: "trogers3k@globo.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Howard Clark",
    email: "hclark3l@icq.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Marie Hicks",
    email: "mhicks3m@stumbleupon.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Jerry Wilson",
    email: "jwilson3n@cpanel.net",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Doris Rogers",
    email: "drogers3o@walmart.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Ronald Carroll",
    email: "rcarroll3p@ca.gov",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Annie Sims",
    email: "asims3q@auda.org.au",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Melissa Miller",
    email: "mmiller3r@acquirethisname.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Gary Dixon",
    email: "gdixon3s@vk.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Brandon Spencer",
    email: "bspencer3t@earthlink.net",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Michael Bailey",
    email: "mbailey3u@nba.com",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Walter Graham",
    email: "wgraham3v@loc.gov",
    cohort_id: 7,
    created_at: "2/1/2016",
    updated_at: "2/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Juan Jordan",
    email: "jjordan3w@sphinn.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Helen Robinson",
    email: "hrobinson3x@howstuffworks.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Joan Shaw",
    email: "jshaw3y@sakura.ne.jp",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Judith Murphy",
    email: "jmurphy3z@parallels.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Lori Owens",
    email: "lowens40@google.pl",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Judy Greene",
    email: "jgreene41@deviantart.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Russell Smith",
    email: "rsmith42@theguardian.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Carl Jacobs",
    email: "cjacobs43@shop-pro.jp",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "James Russell",
    email: "jrussell44@twitpic.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Norma Ramirez",
    email: "nramirez45@360.cn",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "George Gutierrez",
    email: "ggutierrez46@yahoo.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Sharon Montgomery",
    email: "smontgomery47@intel.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Andrea Carr",
    email: "acarr48@squidoo.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Kenneth Brown",
    email: "kbrown49@house.gov",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Mary Snyder",
    email: "msnyder4a@google.fr",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Martin Hill",
    email: "mhill4b@slashdot.org",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Lois Perry",
    email: "lperry4c@forbes.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Lawrence Shaw",
    email: "lshaw4d@biblegateway.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Kenneth Ferguson",
    email: "kferguson4e@indiegogo.com",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: FALSE
  },
  {
    name: "Joshua Brown",
    email: "jbrown4f@state.tx.us",
    cohort_id: 8,
    created_at: "3/1/2016",
    updated_at: "3/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: FALSE
  },
  {
    name: "Virginia Simmons",
    email: "vsimmons4g@netscape.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Martha Porter",
    email: "mporter4h@timesonline.co.uk",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Christina Wells",
    email: "cwells4i@mapquest.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Charles Harper",
    email: "charper4j@imdb.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Heather Hunter",
    email: "hhunter4k@github.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Jonathan Wells",
    email: "jwells4l@newsvine.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Richard Johnston",
    email: "rjohnston4m@oakley.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Patricia Gray",
    email: "pgray4n@pcworld.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Robin Bowman",
    email: "rbowman4o@yahoo.co.jp",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Laura George",
    email: "lgeorge4p@ca.gov",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Steven Woods",
    email: "swoods4q@google.ca",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Carol Hunter",
    email: "chunter4r@wunderground.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Adam Hernandez",
    email: "ahernandez4s@shinystat.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Ryan Larson",
    email: "rlarson4t@howstuffworks.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Heather Scott",
    email: "hscott4u@slideshare.net",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Melissa Cunningham",
    email: "mcunningham4v@boston.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Eugene Rice",
    email: "erice4w@nyu.edu",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Jason George",
    email: "jgeorge4x@constantcontact.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Russell Martin",
    email: "rmartin4y@elegantthemes.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Elizabeth Cunningham",
    email: "ecunningham4z@techcrunch.com",
    cohort_id: 9,
    created_at: "4/1/2016",
    updated_at: "4/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Lois Castillo",
    email: "lcastillo50@github.io",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Joshua Bell",
    email: "jbell51@devhub.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Lisa Bryant",
    email: "lbryant52@thetimes.co.uk",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Walter Dean",
    email: "wdean53@dell.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Chris Richardson",
    email: "crichardson54@parallels.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Christopher Marshall",
    email: "cmarshall55@acquirethisname.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Angela Pierce",
    email: "apierce56@msu.edu",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Robert Mccoy",
    email: "rmccoy57@freewebs.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Kelly Spencer",
    email: "kspencer58@bravesites.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Judy Richards",
    email: "jrichards59@apache.org",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Phyllis Burton",
    email: "pburton5a@cbslocal.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Kimberly Stewart",
    email: "kstewart5b@google.ru",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Gregory Payne",
    email: "gpayne5c@dedecms.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Beverly Butler",
    email: "bbutler5d@cdbaby.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Todd Medina",
    email: "tmedina5e@google.co.uk",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Juan Myers",
    email: "jmyers5f@cdbaby.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Howard Berry",
    email: "hberry5g@fema.gov",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Frank Hicks",
    email: "fhicks5h@state.tx.us",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Benjamin Ruiz",
    email: "bruiz5i@dagondesign.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Marie Mason",
    email: "mmason5j@marketwatch.com",
    cohort_id: 10,
    created_at: "5/1/2016",
    updated_at: "5/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Robert Boyd",
    email: "rboyd5k@netlog.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Ronald Hawkins",
    email: "rhawkins5l@vimeo.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Kenneth Griffin",
    email: "kgriffin5m@goo.ne.jp",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Joseph Gardner",
    email: "jgardner5n@hatena.ne.jp",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Jane Ortiz",
    email: "jortiz5o@blog.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Tammy Rice",
    email: "trice5p@skyrock.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Larry Foster",
    email: "lfoster5q@dyndns.org",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Anthony Spencer",
    email: "aspencer5r@wired.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Randy Thompson",
    email: "rthompson5s@jalbum.net",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Gloria Lewis",
    email: "glewis5t@gnu.org",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Todd Rogers",
    email: "trogers5u@upenn.edu",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Debra Marshall",
    email: "dmarshall5v@deviantart.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Timothy Cook",
    email: "tcook5w@europa.eu",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Charles Knight",
    email: "cknight5x@storify.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Dorothy Lane",
    email: "dlane5y@wikimedia.org",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Margaret Parker",
    email: "mparker5z@google.co.jp",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Keith Wright",
    email: "kwright60@networksolutions.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Sarah Freeman",
    email: "sfreeman61@bloglovin.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Christine Hudson",
    email: "chudson62@fotki.com",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Clarence Lee",
    email: "clee63@behance.net",
    cohort_id: 11,
    created_at: "6/1/2016",
    updated_at: "6/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Annie Scott",
    email: "ascott64@usa.gov",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Aaron Carr",
    email: "acarr65@histats.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Jose Russell",
    email: "jrussell66@hud.gov",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Barbara Long",
    email: "blong67@behance.net",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Ryan Flores",
    email: "rflores68@mit.edu",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Roy Wheeler",
    email: "rwheeler69@prlog.org",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Fred Vasquez",
    email: "fvasquez6a@jigsy.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Brenda Morgan",
    email: "bmorgan6b@wikia.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Anthony Robertson",
    email: "arobertson6c@senate.gov",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Jane Meyer",
    email: "jmeyer6d@chicagotribune.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Christopher Olson",
    email: "colson6e@irs.gov",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Antonio Powell",
    email: "apowell6f@independent.co.uk",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "David Reed",
    email: "dreed6g@sciencedaily.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Timothy Barnes",
    email: "tbarnes6h@jiathis.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Alice Stephens",
    email: "astephens6i@dagondesign.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  },
  {
    name: "Laura Watson",
    email: "lwatson6j@plala.or.jp",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Amy Alvarez",
    email: "aalvarez6k@so-net.ne.jp",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Nicole Gardner",
    email: "ngardner6l@phoca.cz",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: TRUE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Daniel Freeman",
    email: "dfreeman6m@tamu.edu",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: FALSE,
     active: TRUE
  },
  {
    name: "Jonathan Palmer",
    email: "jpalmer6n@rediff.com",
    cohort_id: 12,
    created_at: "7/1/2016",
    updated_at: "7/1/2016",
    password: "asdfasdf",
    happy: FALSE,
     help: TRUE,
     active: TRUE
  }])
Alert.create!([
  {cohort_id: nil, location_id: nil, stack_id: nil, message: "Deadline for 3rd stack signup approaching"},
  {cohort_id: nil, location_id: nil, stack_id: nil, message: "The Dojo will be closed Aug 27-Sept 1"},
  {cohort_id: nil, location_id: nil, stack_id: nil, message: "Thursday Tech talk: Alan Summers, stories from my childhood"}
  ])


Stack.create!([
  {instructor_id: 1, language_id: 2, start_date: "2016-08-01", active: true, location_id: 1, total_assignments: nil},
  {instructor_id: 1, language_id: 1, start_date: "2016-08-01", active: true, location_id: 4, total_assignments: nil},
  {instructor_id: 1, language_id: 3, start_date: "2016-09-01", active: false, location_id: 1, total_assignments: nil},
  {instructor_id: 1, language_id: 2, start_date: "2016-07-01", active: false, location_id: 1, total_assignments: nil}
])
StackStudent.create!([
  {student_id: 1, stack_id: 1, order: 1, belt: "none", assignment_count: nil},
  {student_id: 4, stack_id: 2, order: 1, belt: "black", assignment_count: nil},
  {student_id: 5, stack_id: 2, order: 1, belt: "black", assignment_count: nil},
  {student_id: 6, stack_id: 2, order: 1, belt: "black", assignment_count: nil},
  {student_id: 4, stack_id: 3, order: 2, belt: "black", assignment_count: nil},
  {student_id: 5, stack_id: 3, order: 2, belt: "black", assignment_count: nil},
  {student_id: 6, stack_id: 3, order: 2, belt: "black", assignment_count: nil},
  {student_id: 4, stack_id: 4, order: 3, belt: "black", assignment_count: nil},
  {student_id: 5, stack_id: 4, order: 3, belt: "black", assignment_count: nil},
  {student_id: 6, stack_id: 4, order: 3, belt: "red", assignment_count: nil}
])
