class Stack < ActiveRecord::Base
  belongs_to :instructor
  belongs_to :language
  has_many :student_stacks
  has_many :students, through: :student_stacks
end


# See https://help.github.com/articles/ignoring-files for more about ignoring files.
#
# If you find yourself ignoring temporary files generated by your text editor
# or operating system, you probably want to add a global ignore instead:
#   git config --global core.excludesfile '~/.gitignore_global'

# Ignore bundler config.
/.bundle

# Ignore all logfiles and tempfiles.
/log/*
!/log/.keep
/tmp
